# Generated by Django 3.2.25 on 2024-05-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_imgs/noimage.png', null=True, upload_to='product_imgs/'),
        ),
    ]
