# Generated by Django 3.2.25 on 2024-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240512_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_imgs/noimage.png', null=True, upload_to='product_imgs/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
