# Generated by Django 3.2.25 on 2024-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240512_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Enter comma-separated colors', max_length=100, null=True),
        ),
    ]
